### ISSUE TITLE
use of plugin for only deploy frontend

### ISSUE THREAD

**Issue by adumat** [rogersgt/serverless-frontend-plugin#19]
Hi

Can i use your plugin for only deploy the frontend?

I've already try, but serverless also create a stack for the lambda (not configured) and subsequent deploy always fail with message: 

> Created change set does not include any changes, removing it

<details>
  <summary>my serverless configuration</summary>
import type { Serverless } from 'serverless/aws';
import { env } from './environment';

console.log(`-------------- USING ENV: ${env.stage} ----------------`);

const serverlessConfiguration: Partial<Serverless> = {
  frameworkVersion: '3',
  org: '----',
  app: '-------',
  service: '---------',
  configValidationMode: 'error',
  plugins: ['serverless-offline', 'serverless-frontend-plugin'],
  provider: {
    name: 'aws',
    runtime: 'nodejs16.x',
    profile: env.profile,
    stage: env.stage,
    region: env.region,
    environment: env,
  },
  custom: {
    'serverless-frontend-plugin': {
      distDir: 'build',
      build: {
        command: ['yarn', 'build'],
        env: env,
      },
      distribution: {
        dnsName: env.FRONTEND_DOMAIN_NAME,
        acmCertificateArn: env.ACM_CERTIFICATE_ARN,
        hostedZoneName: env.HOSTED_ZONE,
      },
      offline: {
        command: ['yarn', 'dev'],
        env: env,
      },
    },
  },
};

module.exports = serverlessConfiguration;
</details>

**Comment by rogersgt** [comment]
Hi @adumat thanks for taking a look at this plugin. This was intended purely for the use with the `serverless` framework, which is purely a backend framework built with AWS Lambda, Google Functions, etc. This plugin simply augments our serverless API's in order to support full Single Page Applications.

For your use case, if you simply need the Cloudfront CloudFormation, you are welcome to copy or reference the cloudformation template from the source code here: https://github.com/rogersgt/serverless-frontend-plugin/blob/master/templates/aws-cloudfront.json
